
dist: xenial

language: python

matrix:
  include:
    - python: '3.10'
    - python: '3.11'
    - python: '3.12'

install:
  - python -m pip install --upgrade pip
  - pip install -r requirements.txt

script:
  - pytest tests --cov-branch