language: python

matrix:
  include:
    - python: '3.10'
    - python: '3.11'
    - python: '3.12'

before_install:
- python -m pip install --upgrade pip

install:
  - pip install -r requirements.txt

script:
  - pytest tests --cov-branch