[tool.poetry]
name = "chickenstats"
version = "1.7.3.8.9.10.25"
description = "Python library for scraping & analyzing sports statistics"
authors = ["chickenandstats <chicken@chickenandstats.com>"]
license = "GPL-3.0-only"
packages = [{include = "chickenstats"},
            {include = "chickenstats/chicken_nhl"},
            {include = "chickenstats/evolving_hockey"},
            {include = "chickenstats/capfriendly"},]
maintainers = ["chickenandstats <chicken@chickenandstats.com>"]
readme = "README.md"
repository = "https://github.com/chickenandstats/chickenstats"
documentation = "https://www.chickenstats.com"

[tool.poetry.dependencies]
python = "^3.11"
requests = "^2.31.0"
pandas = "^2.1.4"
numpy = "^1.26.2"
beautifulsoup4 = "^4.12.2"
lxml = "^4.9.4"
Unidecode = "^1.3.7"
shapely = "^2.0.2"
scikit-learn = "^1.3.2"
geopandas = "^0.14.1"
rich = "^13.7.0"


[tool.poetry.group.dev]
optional = true

[tool.poetry.group.dev.dependencies]
xgboost = "^2.0.3"
mlflow = "^2.9.2"
optuna = "^3.5.0"
python-dotenv = "^1.0.0"
black = "^23.12.1"
ruff = "^0.1.9"
jupyter = "^1.0.0"
pytest-cov = "^4.1.0"


[tool.poetry.group.test]
optional = true

[tool.poetry.group.test.dependencies]
pytest = "^7.4.3"


[tool.poetry.group.docs]
optional = true

[tool.poetry.group.docs.dependencies]
mkdocs = "^1.5.3"
mkdocs-material = "^9.5.3"

[tool.pytest.ini_options]
testpaths = ["tests",]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
