authors:
  - chicken
social:
  cards_layout_options:
    background_color: transparent
    background_image: layouts/backgrounds/default.png
categories:
  - xG
tags:
  - hockey
  - chickenstats
  - "xG model"
