
name: build

on:
  push:
    branches:
      - main
  workflow_call:

jobs:

  tests:
    if: ${{ github.ref_type != 'tag' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-cov
          pipx install poetry
      - name: Run tests
        run: |
          pytest --cov-branch --cov=chickenstats --cov-report=html
      - name: Upload htmlcov artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage_report
          path: htmlcov/

  build:
    runs-on: ubuntu-latest
    needs: [tests]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-cov
          pipx install poetry
      - name: Build package
        run: poetry build


