
name: docs

on:
  release:
    types:
      - published

permissions:
  contents: write

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.12
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        sudo apt-get install pngquant 
        sudo apt-get install rsync
        pip install git+https://${GH_TOKEN}@github.com/squidfunk/mkdocs-material-insiders.git
        pip install mkdocstrings-python mike
    - name: Build docs
      run: mkdocs build
    - name: Mike deploy
      run: |
        echo "$GH_TAG" | tr -d "v" | cut -c1-3
        TAG=`echo "$GH_TAG" | tr -d "v" | cut -c1-3`
        git config user.name chickenandstats
        git config user.email chicken@chickenandstats.com
        git fetch origin gh-pages --depth=1
        mike deploy "$TAG" latest --update-aliases --push -t latest
        mike set-default --push latest

  gcp-upload:
    needs: [ build-docs ]
    permissions:
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout gh-pages
        uses: actions/checkout@v4
        with:
          ref: 'gh-pages'
      - name: gcloud authentication
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'
      - name: Set up Cloud SDK
        uses: 'google-github-actions/setup-gcloud@v2'
      - name: Delete files from bucket
        run: gsutil -m rm -a gs://chickenstats.com/**
      - name: Creating gcloudignore
        run: |
          touch .gcloudignore
          echo '.git/' >> .gcloudignore
          echo '.idea/' >> .gcloudignore
          echo '**gha-creds-*.json' >> .gcloudignore
          echo '.gcloudignore' >> .gcloudignore
      - name: gcloud upload
        uses: 'google-github-actions/upload-cloud-storage@v2'
        with:
          path: '.'
          destination: 'chickenstats.com'

env:
  GH_TOKEN: ${{ secrets.GH_TOKEN }}
  GH_TAG: ${{ github.ref_name }}
