
name: docs

on:
  release:
    types:
      - published
  push:
    branches:
      - test

permissions:
  contents: write

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.12
      uses: actions/setup-python@v3
      with:
        python-version: '3.12'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        sudo apt-get install pngquant 
        sudo apt-get install rsync
        pip install git+https://${GH_TOKEN}@github.com/squidfunk/mkdocs-material-insiders.git
        pip install mkdocstrings-python mike
    - name: Build docs
      run: mkdocs build
    #- name: Mike deploy
    #  run: |
    #    git config user.name chickenandstats
    #    git config user.email chicken@chickenandstats.com
    #    git fetch origin gh-pages --depth=1
    #    mike deploy --push --update-aliases 1.7 latest
    - name: Display structure of files
      run: ls -R -a
    - name: Create SSH key
      run: |
        mkdir -p ~/.ssh/
        echo "$SSH_PRIVATE_KEY" > ../private.key
        sudo chmod 600 ../private.key
        echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
      shell: bash
      env:
        SSH_PRIVATE_KEY: ${{secrets.SSH_PRIVATE_KEY}}
        SSH_KNOWN_HOSTS: ${{secrets.SSH_KNOWN_HOSTS}}
    - name: Copy remote files
      run: |
        rsync -a --inplace --delete ./site/ $SSH_USER@$SSH_HOST:$SSH_DESTINATION -e 'ssh -i ${{ github.workspace }}/../private.key'
      shell: bash
      env:
        SSH_USER: ${{secrets.SSH_USER}}
        SSH_HOST: ${{secrets.SSH_HOST}}
        SSH_DESTINATION: ${{secrets.SSH_DESTINATION}}

env:
  GH_TOKEN: ${{ secrets.GH_TOKEN }}
