
name: docs

on:
  push:

permissions:
  contents: write

jobs:
  docs:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.12
      uses: actions/setup-python@v3
      with:
        python-version: '3.12'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        sudo apt-get install pngquant 
        sudo apt-get install rsync
        pip install git+https://${GH_TOKEN}@github.com/squidfunk/mkdocs-material-insiders.git
        pip install mkdocstrings-python
    - name: Build docs
      run: mkdocs build
    - name: Create SSH key
      run: |
        mkdir -p ~/.ssh/
        echo "$SSH_PRIVATE_KEY" > ../private.key
        sudo chmod 600 ../private.key
        echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
      shell: bash
      env:
        SSH_PRIVATE_KEY: ${{secrets.SSH_PRIVATE_KEY}}
        SSH_KNOWN_HOSTS: ${{secrets.SSH_KNOWN_HOSTS}}
        SSH_KEY_PATH: ${{ github.workspace }}/../private.key
    - name: Copy remote files
      run: |
        sudo chmod 600 ${{ github.workspace }}/../private.key
        rsync -a ~/site ${{secrets.SSH_USER}}@${{secrets.SSH_HOST}}:${{secrets.SSH_DESTINATION}} -e ${{ github.workspace }}/../private.key
      shell: bash

env:
  GH_TOKEN: ${{ secrets.GH_TOKEN }}
