# GitHub workflow file that tests package in Python version 3.10 - 3.12
name: docs-testing

# Trigger the action when releases are published
on:
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  docs:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.12
      uses: actions/setup-python@v3
      with:
        python-version: '3.12'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        sudo apt-get install pngquant 
        sudo apt-get install rsync
        pip install git+https://${GH_TOKEN}@github.com/squidfunk/mkdocs-material-insiders.git
        pip install mkdocstrings-python
        pip install mike
    - name: Creating Git user
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
    #- name: Getting version for documents
    #  run: export DOC_VERSION=${${{github.ref_name}}:1:3}
    - name: Setting up Mike docs
      run: mike deploy --push --update-aliases 1.7 latest
    - name: Build docs
      run: mkdocs build
    - name: Create SSH key
      run: |
        mkdir -p ~/.ssh/
        echo "$SSH_PRIVATE_KEY" > ../private.key
        sudo chmod 600 ../private.key
        echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
      shell: bash
      env:
        SSH_PRIVATE_KEY: ${{secrets.SSH_PRIVATE_KEY}}
        SSH_KNOWN_HOSTS: ${{secrets.SSH_KNOWN_HOSTS}}
        SSH_KEY_PATH: ${{ github.workspace }}/../private.key
    - name: Copy remote files
      run: |
        rsync -a --inplace --delete ./site/ ${{secrets.SSH_USER}}@${{secrets.SSH_HOST}}:${{secrets.SSH_DESTINATION}} -e 'ssh -i ${{ github.workspace }}/../private.key'
      shell: bash

env:
  GH_TOKEN: ${{ secrets.GH_TOKEN }}
