
name: docs

on:
  release:
    types:
      - published

permissions:
  contents: write

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.12
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        sudo apt-get install pngquant 
        sudo apt-get install rsync
        pip install git+https://${GH_TOKEN}@github.com/squidfunk/mkdocs-material-insiders.git
        pip install mkdocstrings-python mike
    - name: Build docs
      run: mkdocs build
    - name: Mike deploy
      run: |
        TAG=`echo "$GH_TAG" | tr -d "v"`
        git config user.name chickenandstats
        git config user.email chicken@chickenandstats.com
        git fetch origin gh-pages --depth=1
        mike deploy $TAG latest --update-aliases --push
        mike set-default --push latest

env:
  GH_TOKEN: ${{ secrets.GH_TOKEN }}
  GH_TAG: ${{github.ref_name}}
