
name: new-release

on:
  release:
    types: [published]

jobs:

  lint_format:
    uses: ./.github/workflows/lint_format.yml

  tests:
    needs: [lint_format]
    uses: ./.github/workflows/tests.yml

  build:
    needs: [lint_format, tests, docs]
    uses: ./.github/workflows/build.yml

  publish:
    needs: [ lint_format, tests, build ]
    uses: ./.github/workflows/publish.yml