
name: new-release

on:
  release:
    types: [published]
  workflow_run:
    workflows: [ "tests" ]
    branches: [ main ]
    types:
      - completed

jobs:

  build:
    uses: ./.github/workflows/build.yml

  publish:
    needs: [lint_format, tests, build]
    uses: ./.github/workflows/publish.yml