
name: new-release

on:
  release:
    types: [published]

jobs:

  tests:
    uses: ./.github/workflows/tests.yml

  docs:
    needs: [tests]
    uses: ./.github/workflows/docs.yml

  build:
    needs: [tests, docs]
    uses: ./.github/workflows/build.yml