
name: new-release

on:
  release:
    types: [published]

jobs:

  tests:
    uses: ./.github/workflows/tests.yml

  build:
    needs: [tests, build]
    uses: ./.github/workflows/build.yml

  publish:
    needs: [tests, build]
    uses: ./.github/workflows/publish.yml