# GitHub workflow file that tests package in Python version 3.10 - 3.12
name: build

# Trigger the action when releases are published
on:
  push:
    branches:
      - test
  workflow_call:
  workflow_dispatch:

jobs:

  # Setting up test environment
  test:

    strategy:
      # We don't want the worker to fail because the job is taking too long
      fail-fast: false
      # This is the testing matrix
      matrix:
        # There will be three tests, one for each Python and tox environment
        python: ['3.10', '3.11', '3.12']
        os: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Homebrew
        if: matrix.os == 'macos-latest'
        uses: Homebrew/actions/setup-homebrew@master

      - name: Install libomp
        if: matrix.os == 'macos-latest'
        run: brew install libomp

      - name: Install uv
        uses: astral-sh/setup-uv@v2

      - name: Set up Python
        run: uv python install ${{ matrix.python }}

      - name: Install the project
        run: uv sync --all-extras --dev

      - name: Install tox
        run: uv pip install tox-gh
        env:
          GITHUB_ACTIONS: true

      - name: Run tox
        run: uv run tox -c tox.ini
        env:
          GITHUB_ACTIONS: true

      - name: Upload coverage file
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: ./.coverage

      - name: Upload coverage html
        uses: actions/upload-artifact@v4
        with:
          name: coverage-html
          path: ./coverage_html

  report:
    runs-on: ubuntu-latest
    # The job depends on the test job completing successfully
    needs: [ test ]
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v2

      - name: Set up Python
        run: uv python install ${{ matrix.python }}

      - name: Install the project
        run: uv sync --all-extras --dev

      - name: Download coverage file
        uses: actions/download-artifact@v4
        with:
          name: coverage
          path: ./

      - name: Download coverage html
        uses: actions/download-artifact@v4
        with:
          name: coverage-html
          path: ./coverage_html
          
      - name: Display structure of downloaded files
        run: ls -R
          
      - name: Display structure of files
        run: ls -R -a
        
      - name: Generate reports
        run: |
          uvx coverage report
          uvx coverage xml 
          uvx coverage html
          
      # Upload the artifacts
      - name: Upload htmlcov artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage_report
          path: htmlcov/
          
      - name: Upload coverage artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: .coverage
          
      # Upload the code coverage reports to the reporting service
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.2.0
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}


