# GitHub workflow file that tests package in Python version 3.10 - 3.12
name: build

# Trigger the action when releases are published
on:
  push:
    branches:
      - test
  workflow_call:
  workflow_dispatch:

jobs:

  # Setting up test environment
  test:

    strategy:
      # We don't want the worker to fail because the job is taking too long
      fail-fast: false
      # This is the testing matrix
      matrix:
        # There will be three tests, one for each Python and tox environment
        py:
          - "3.12"
          - "3.11"
          - "3.10"
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Homebrew
        if: matrix.os-alt == 'mac'
        uses: Homebrew/actions/setup-homebrew@master

      - name: Install libomp
        if: matrix.os-alt == 'mac'
        run: brew install libomp

      - name: Install uv
        uses: astral-sh/setup-uv@v2

      - name: Set up Python
        run: uv python install ${{ matrix.python }}

      - name: Install the project
        run: uv sync --all-extras --dev

      - name: Run tox
        # Make sure we pull from the test matrix
        run: uvx tox -c tox.ini
        env:
          GITHUB_ACTIONS: true

      # Upload the coverage artifact so we can combine it later
      - name: Upload coverage artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage-html
          path: ./coverage_html

      # Upload the coverage artifact so we can combine it later
      - name: Upload coverage artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage-xml
          path: ./coverage.xml

      # Upload the code coverage reports to the reporting service
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.2.0
        env:
          files: ./coverage.xml
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}


