name: Tests

on:
  push:
    branches:
      - 'main'

jobs:

  clean:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12
      - name: Install tox and any other packages
        run: |
          pip install --upgrade pip
          pip install tox
          pip install pytest
          pip install pytest-cov
      - name: Run tox
        run: tox -e clean

  test:

    runs-on: ubuntu-latest

    needs: clean

    strategy:
      fail-fast: false
      matrix:
        include:
          - python: '3.10'
            tox: 'py310'
          - python: 3.11
            tox: 'py311'
          - python: 3.12
            tox: 'py312'

    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}
      - name: Install tox and any other packages
        run: |
          pip install --upgrade pip
          pip install tox
          pip install pytest
          pip install pytest-cov
      - name: Run tox
        run: tox -e ${{ matrix.tox }}
      - name: Generate coverage
        run: coverage xml
      - name: Upload Coverage artifact
        uses: actions/upload-artifact@v3
        with:
          name: coverage
          path: coverage.xml

  report:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12
      - name: Download math result for job 1
        uses: actions/download-artifact@v3
        with:
          name: coverage
      - name: Install tox and any other packages
        run: |
          pip install --upgrade pip
          pip install tox
          pip install pytest
          pip install pytest-cov
      - name: Run tox
        run: tox -e report

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
