
name: update-docs

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  docs:
    permissions:
      contents: 'read'
      id-token: 'write'

    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
    - name: Set up Python 3.12
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        sudo apt-get install pngquant 
        pip install git+https://${GH_TOKEN}@github.com/squidfunk/mkdocs-material-insiders.git
        pip install mkdocstrings-python mike
    - name: Build docs
      run: mkdocs build
    - name: Mike deploy
      run: |
        git config user.name chickenandstats
        git config user.email chicken@chickenandstats.com
        git fetch origin gh-pages --depth=1
        mike deploy "$DOC_VERSION" latest --update-aliases --push
        mike set-default --push latest
    - name: Checkout gh-pages
      uses: actions/checkout@v4
      with:
        ref: 'gh-pages'
    - name: gcloud authentication
      uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'
    - name: Set up Cloud SDK
      uses: 'google-github-actions/setup-gcloud@v2'
    - name: Delete files from bucket
      run: gsutil rm gs://chickenstats-docs/**
    - name: gcloud upload
      uses: 'google-github-actions/upload-cloud-storage@v2'
      with:
        destination: 'chickenstats-docs'

env:
  GH_TOKEN: ${{ secrets.GH_TOKEN }}
  GH_TAG: ${{github.ref_name}}
  DOC_VERSION: 1.7.6
